# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [nasa, trojan]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username turbo
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username Fox-fi
issuehunt: # Replace with a single IssueHunt username mouse36872
otechie: # Replace with a single Otechie username charlie
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://bestbuy.com','https://mycreed.io','https://azure.com','https://pornhub.com','https://knightlinelegal.com']
